parameters:
  - name: env
    type: string
  - name: org
    type: string
  - name: subscriptions
    type: object
  - name: nameFormat
    type: string
  - name: resourceGroupTypeName
    type: string
    default: 'rg'
  - name: functionsTypeName
    type: string
    default: 'func'
  - name: vnetTypeName
    type: string
    default: 'vnet'
  - name: subnetTypeName
    type: string
    default: 'subnet'

variables:
  - name: env
    value: ${{ parameters.env }}
  - name: varOrg
    value: ${{ parameters.org }}
  - name: varSubscriptions
    value: ${{ parameters.subscriptions }}
  - name: varNameFormat
    value: ${{ parameters.nameFormat }}
  - name: varResourceGroupTypeName
    value: ${{ parameters.resourceGroupTypeName }}
  - name: varFunctionsTypeName
    value: ${{ parameters.functionsTypeName }}
  - name: varVnetTypeName
    value: ${{ parameters.vnetTypeName }}
  - name: varSubnetTypeName
    value: ${{ parameters.subnetTypeName }}
