parameters:
  - name: stage
    type: string
  - name: job
    type: string

steps:
  - task: PowerShell@2
    name: retrieve
    displayName: Retrieve environments
    inputs:
      filePath: pipeline-templates/global/scripts/get-environments.ps1
      arguments: -Stage ${{ parameters.stage }} -Job ${{ parameters.job }}
      pwsh: true